### ISSUE TITLE
Code completion on structs (not working)

### ISSUE THREAD

**Issue by rasgo-cc** [kube/vscode-clang-complete#12] opened 2016-11-22 10:15 UTC
Hi,

In C structs, code completion is not working as expected.
Test code:
```
typedef struct 
{
	char a;
	int b;
} test_t;

int main(int argc, char const* argv[])
{
	test_t var;
	var. // doesn't show test_t variables but everything parsed by clang
}
```

However, if I declare var as a pointer, when writing "->" it triggers the corrent code completion words (i.e only the variable names, "a" and "b")

**Comment by kube** [comment] 2016-11-22 12:29
I just checked your example and it works fine for me.

![output](https://cloud.githubusercontent.com/assets/2991143/20523681/84c20b90-b0b6-11e6-81d3-df17a52a8e78.gif)

Can you tell me which version of Clang you are using and on which OS?

This extension seems to have some issues, and I will fix them once I finish my current mission next month. And I will take time to add features too.

**Comment by rasgo-cc** [comment] 2016-11-22 12:52
Weird... I just downloaded the latest one: 3.9.0.
I'm on Windows 10, Visual Studio Code 1.7.1, if that matters.

(by the way how to you take these GIF screenshots? :) )

**Comment by kube** [comment] 2016-11-22 13:05
How did you install Clang on Windows 10?

I'll need to check the extension on Linux and Windows too, and I plan to make the extension really better than it is now.

For the screenshots, I use **QuickTime** to create a `.mov` and then [**FFmpeg**](https://www.ffmpeg.org/) to convert to a `.gif`.

**Comment by rasgo-cc** [comment] 2016-11-22 13:38
I downloaded the pre-built binaries from the Clang's website: http://llvm.org/releases/download.html
Clang for Windows 64bit

I also have to say that, other than this small bug, I'm already quite happy with this extension. Let me know if I can help on the Windows side.

**Comment by kube** [comment] 2016-11-22 21:10
The first thing would be to identify exactly the issue to be able to reproduce it before fixing it.

As you can see in https://github.com/kube/vscode-clang-complete/issues/10, issues on this extension seem to differ on each platform, that's why I should test it on Windows and Linux myself to be able to debug easily.

But I would really appreciate if you can find what is the issue exactly here, and if you can do the same test case on the same project on macOS or Linux if you have one available on your computer to tell me if this behaviour is linked to Windows.

**Comment by rasgo-cc** [comment] 2016-11-25 06:20
I'm really really short on time and I know nothing about TypeScript but at the same time I really would like to have this working. Any hints on how to debug this? Any debug flag I can set so I can see clang's output while I type?

**Comment by kube** [comment] 2016-11-25 11:32
I just re-installed Windows 10 on my Mac, and I'm gonna install Clang and setup everything to be able to test my extension.

I'm not gonna do this today, but I'm gonna try tomorrow or Sunday.

**Comment by kube** [comment] 2016-11-25 12:46
Ok, so I just installed Clang and VSCode, then tried the same example.

It works for me on Windows 10 too.

![test](https://cloud.githubusercontent.com/assets/2991143/20625703/4cd50ff0-b315-11e6-8e04-729142b61e4c.gif)

Are you using the extension on a particular project? Or do you have the error on this same configuration?

**Comment by rasgo-cc** [comment] 2016-11-26 00:38
OK got it! I reinstalled VSCode and removed all settings, installed this extension and it works.
What I found is that what I described here happens when you also have the C/C++ extension installed (the one by - and recommended by - Microsoft).

In that case the "var." gets (badly) completed by Microsoft's extension (it just presents every symbol it can find in the workspace, not really a completion) and with "p_var->" (`test_t *p_var = &var`) the completion is done by this extension.

Not sure what workaround can be implemented unless uninstalling the C/C++ extension though...

I'm also missing these two features:
1) Code completion for function parameters
2) Goto definition 

I really want to shift to vscode but so far I guess I'll have to stick with ST3. I'm currently using "EasyClangComplete": https://packagecontrol.io/packages/EasyClangComplete
Maybe you can get some ideas from it.

**Comment by kube** [comment] 2016-11-26 12:01
These packages **can not work together**, as they **both provide completion** for C/C++ code.

And they do that in a different way:
- The completion from Microsoft seems to work like `GNU Global` and is not context-aware.
- This one uses Clang, which provides a pretty-good completion by using the front-end compiler which does a static analysis and so gives back a precise and semantic-aware completion.

For these two features you miss: that's part of what I want to add once I get time.
They will need some extra-stuff to be done before, but I'm willing to do it.

I'll check **EasyClangComplete** to see how they do, and what features they provide, but I already have a pretty good idea of what I'm gonna do on this extension, and how.

**Comment by rasgo-cc** [comment] 2016-11-28 01:34
By no means I wanted to put pressure on you, I think so far you've done a great job. Unfortunately I won't be able to help you with code since I lack the skills (amateur javascripter, zero typescript, just a few notions about clang) but if you need a tester or feedback, count me in!

**Comment by kube** [comment] 2016-12-04 14:55
Don't worry you do not put pressure on me, I'm happy to see people interested in this project.

I just have a lot of work on my current mission and I just wanna finish it before updating this extension. I see you are watching the repo, so you'll see notifications when I'll update it (asap).

I'm gonna close this issue as it's not a bug of the extension but a collision with other completion extensions.

I create new feature request issues for **Completion for function parameters**, and **Goto definition**.

**Closed as completed** 2016-12-04 14:55 UTC
